name: Run Stock Data Fetcher
on:
  schedule:
    - cron: '0 18 * * 1-5'
  workflow_dispatch:
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Script
      run: python test.py
    - name: Commit and Push
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit Changes
      run: |
        git config user.name "github-actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add out.csv
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Update stock data"
          git push
        fi