name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: python test.py
    - uses: actions/upload-artifact@v3
      with:
        name: output-file
        path: output.csv