name: Run test.py
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python test.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: csv-files
        path: |
          yahooClean.csv
          unClean.csv