name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python test.py
      - name: Upload clean artifact
        uses: actions/upload-artifact@v4
        with:
          name: yahooClean
          path: yahooClean.csv
      - name: Upload unclean artifact
        uses: actions/upload-artifact@v4
        with:
          name: unClean
          path: unClean.csv