name: Get NVDA Stock Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Add this permissions block
permissions:
  contents: write # This grants write permission to the workflow for the 'contents' scope

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python script
        run: python get_nvda_data.py

      - name: Commit and push if it changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add x.csv
          git commit -m "Automated NVDA stock data update" -a || echo "No changes to commit"
          git push
