name: Python script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create dummy data.csv
      run: |
        echo "lookup" > data.csv
        echo "AAPL" >> data.csv
        echo "GOOGL" >> data.csv
        echo "MSFT" >> data.csv
    - name: Run script
      run: |
        python test.py
    - name: Upload output artifact
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output.csv
