name: Python CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - run: python test.py
    - uses: actions/upload-artifact@v4
      with:
        name: yahooClean
        path: yahooClean.csv
    - uses: actions/upload-artifact@v4
      with:
        name: unClean
        path: unClean.csv